### PR TITLE
React hook form v6

### PR DESCRIPTION
**Pull request by jtrein**
- [x] Create Membership form @jtrein
- [x] Create Tribute form @jdville03 
- [x] Create Transfer form @jdville03 
- [x] Adapter/Extension Configuration from @sophiacodes

### CODE REVIEW

**Review by sophiacodes — APPROVED** [review]
Looks good from my side, thanks for updating!

**Comment by jtrein** [comment]
@sophiacodes @jdville03 Could you fix up your forms as well?

**Comment by jdville03** [comment]
`CreateTributeProposal` and `CreateTransferProposal` are both good to go on this branch now.

**Review by jdville03 — APPROVED** [review]

**Comment by jtrein** [comment]
Thank you, both!

**Pull request merged**
